"""
    ProjecturedAll

The flat namespace of the kernel, the platform, the console and PDF backends and
the 19 domains, with their submodules as `ProjecturedAll.XxxModule`. The tests, the examples and the REPL of
this repository load it, and so do the downstream repositories. The registry does
not hold it: a user loads `Projectured` and the packages she installed.

The re-exports are generated by the loop of `source/all/ProjecturedAll.jl`,
one pass over the submodules of every source package. Adding a package needs an
edit here: put it in the `import` list and in `_SOURCES`.
"""
module ProjecturedAll

import ProjecturedKernel
import ProjecturedPlatform
import ProjecturedConsole
import ProjecturedPDF

# The concrete domains, in dependency order: the ones that need no other domain,
# then the ones that build on them, then the application on top.
import ProjecturedJSON
import ProjecturedYAML
import ProjecturedXML
import ProjecturedMarkdown
import ProjecturedRST
import ProjecturedBook
import ProjecturedMath
import ProjecturedJulia
import ProjecturedSQL
import ProjecturedDatabase
import ProjecturedGraph
import ProjecturedChart
import ProjecturedSequenceChart
import ProjecturedDBCatalog
import ProjecturedFormula
import ProjecturedFSM
import ProjecturedProcess
import ProjecturedPivot
import ProjecturedWorkflow

include("../../../source/all/ProjecturedAll.jl")

end # module ProjecturedAll
