name = "ProjecturedYaml"
uuid = "a9f201ce-8e0a-436b-92f0-224b8478d5cb"
version = "0.1.0"
authors = []
entryfile = "ProjecturedYaml.jl"

# The YAML source domain.

[deps]
ProjecturedCollection = "8bcd16db-087d-4f4f-9083-436e400a73ed"
ProjecturedFileFormat = "44b08bd6-3ef1-426c-9816-1b2d08d0c221"
ProjecturedDomain = "56e9f339-7147-459f-9ae1-7785cace5f24"
ProjecturedKernel = "a3e3499a-684d-4df9-a0d6-de2d1797b1f3"
ProjecturedPrimitive = "a792d3c9-f446-49ae-a65b-985afeeb5ba4"
ProjecturedProjection = "a1f769f1-b8c6-4a84-a219-e21aa25c8d5d"
ProjecturedStyle = "dbc249a4-36d3-4338-9eae-7cc9f61f07b1"
ProjecturedSyntax = "98402e06-2a56-4e2c-83c3-b2840758e8f3"
ProjecturedText = "2d3f4b4d-5576-4044-8c5c-d91689d6f4b3"

[sources]
ProjecturedCollection = {path = "../../collection/main"}
ProjecturedFileFormat = {path = "../../fileformat/main"}
ProjecturedDomain = {path = "../../domain/main"}
ProjecturedKernel = {path = "../../kernel/main"}
ProjecturedPrimitive = {path = "../../primitive/main"}
ProjecturedProjection = {path = "../../projection/main"}
ProjecturedStyle = {path = "../../style/main"}
ProjecturedSyntax = {path = "../../syntax/main"}
ProjecturedText = {path = "../../text/main"}
