name = "ProjecturedTulip"
uuid = "bf3b10cf-befa-4ac9-98d3-9c1678f27146"
version = "0.1.0"
authors = []

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
ProjecturedLayout = "131aea98-bff0-4be4-86bf-c6e8c408eb61"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"

[compat]
MathOptInterface = "1"
Tulip = "0.9"

[sources]
ProjecturedLayout = {path = "../ProjecturedLayout"}
