name = "ProjecturedVideo"
uuid = "8d225f56-7fda-4c1e-a58b-db6d64f8335c"
version = "0.1.0"
authors = []
entryfile = "ProjecturedVideo.jl"

[deps]
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
ProjecturedDomain = "e0912940-0f50-4a55-a142-7b4aed3d6e35"
ProjecturedSdl = "f0002b97-94ba-416c-b93c-86cdc095626f"

[sources]
ProjecturedDomain = {path = "../../domain/main"}
ProjecturedSdl = {path = "../../sdl/main"}
