# MutableCell — the plain mutable, non-reactive kind. Included into
# `ReactiveModule` (see Reactive.jl).

"""
    MutableCell{T}

A plain mutable box: `c[]` reads, `c[] = v` writes. **No reactive bookkeeping**
— reading it inside a reactive thunk registers no dependency, and writing it
invalidates nothing (by design: this is the high-frequency-mutation kind; a
sync step propagates changes into a reactive shadow when observation is
wanted). `MutableCell(v)` infers `T = typeof(v)` (the `Ref` convention); pass
`MutableCell{T}(v)` for a wider field type.
"""
# NOTE: the param-inferring convenience ctor `MutableCell(v)` is auto-generated by
# Julia from the field (`MutableCell(value::T) where T`); defining it by hand would
# overwrite it and abort precompilation.
mutable struct MutableCell{T} <: AbstractCell{T}
    value::T
end

# A bare, uncounted, unregistered field read/write — no reactive bookkeeping.
Base.getindex(c::MutableCell) = c.value
Base.setindex!(c::MutableCell, value) = (c.value = value)

function Base.show(io::IO, c::MutableCell)
    print(io, "MutableCell(")
    show(io, c.value)
    print(io, ")")
end
