# Fragment of `CellModule` — the plain mutable, non-reactive cell kind.

"""
    MutableCell{T}

A plain mutable box: `c[]` reads, `c[] = v` writes. **No reactive bookkeeping**
— reading it inside a reactive thunk registers no dependency, and writing it
invalidates nothing (by design: this is the high-frequency-mutation kind).
`MutableCell(v)` infers `T = typeof(v)` (the `Ref` convention); pass
`MutableCell{T}(v)` for a wider field type.
"""
# NOTE: the param-inferring convenience ctor `MutableCell(v)` is auto-generated by
# Julia from the field (`MutableCell(value::T) where T`); defining it by hand would
# overwrite it and abort precompilation.
mutable struct MutableCell{T} <: AbstractCell{T}
    value::T
end

# A bare, uncounted, unregistered field read/write — no reactive bookkeeping.
Base.getindex(c::MutableCell) = c.value
Base.setindex!(c::MutableCell, value) = (c.value = value)

# The value is held outright: nothing can be stale, and an untracked read is the
# plain read (there is no dependency to register in the first place).
is_cell_up_to_date(::MutableCell) = true
Base.peek(c::MutableCell) = c[]

function Base.show(io::IO, c::MutableCell)
    print(io, "MutableCell(")
    show(io, c.value)
    print(io, ")")
end
