name = "ProjecturedDbCatalog"
uuid = "b1d9ff6e-938d-43f9-b327-c16571782863"
version = "0.1.0"
authors = []

# The database catalog domain.

[deps]
ProjecturedKernel = "a3e3499a-684d-4df9-a0d6-de2d1797b1f3"
ProjecturedPlatform = "b21cb890-5227-4e91-ae0e-8ab4d844f9f7"
ProjecturedSql = "d8115f9e-353f-406e-8661-6168b14bd6fd"

[sources]
ProjecturedKernel = {path = "../ProjecturedKernel"}
ProjecturedPlatform = {path = "../ProjecturedPlatform"}
ProjecturedSql = {path = "../ProjecturedSql"}
