name = "ProjecturedWorkbench"
uuid = "0f877e1b-20a0-4c5b-94fa-be7570d31986"
version = "0.1.0"
authors = []
entryfile = "ProjecturedWorkbench.jl"

# The workbench application.

[deps]
ProjecturedCollection = "8bcd16db-087d-4f4f-9083-436e400a73ed"
ProjecturedConversation = "99f175d3-497d-4a02-8497-78e6e06c4369"
ProjecturedFileFormat = "44b08bd6-3ef1-426c-9816-1b2d08d0c221"
ProjecturedFileSystem = "d20df666-2dae-4a0b-8892-08ed6c45272c"
ProjecturedJson = "975d7430-285c-49f1-8705-4e3c002513ca"
ProjecturedJulia = "8625b742-6071-4be0-bd92-d89876019251"
ProjecturedKernel = "a3e3499a-684d-4df9-a0d6-de2d1797b1f3"
ProjecturedLayout = "131aea98-bff0-4be4-86bf-c6e8c408eb61"
ProjecturedMarkdown = "0d968d4c-e8d6-48b2-bf35-e636991e1b44"
ProjecturedPrimitive = "a792d3c9-f446-49ae-a65b-985afeeb5ba4"
ProjecturedProjection = "a1f769f1-b8c6-4a84-a219-e21aa25c8d5d"
ProjecturedStyle = "dbc249a4-36d3-4338-9eae-7cc9f61f07b1"
ProjecturedSyntax = "98402e06-2a56-4e2c-83c3-b2840758e8f3"
ProjecturedText = "2d3f4b4d-5576-4044-8c5c-d91689d6f4b3"
ProjecturedWidget = "5a37ff34-8f98-4fd0-b145-c68cb9790819"
ProjecturedXml = "6f8deb26-6771-4202-9df0-376c19aef1c5"
ProjecturedYaml = "a9f201ce-8e0a-436b-92f0-224b8478d5cb"

[sources]
ProjecturedCollection = {path = "../../collection/main"}
ProjecturedConversation = {path = "../../conversation/main"}
ProjecturedFileFormat = {path = "../../fileformat/main"}
ProjecturedFileSystem = {path = "../../filesystem/main"}
ProjecturedJson = {path = "../../json/main"}
ProjecturedJulia = {path = "../../julia/main"}
ProjecturedKernel = {path = "../../kernel/main"}
ProjecturedLayout = {path = "../../layout/main"}
ProjecturedMarkdown = {path = "../../markdown/main"}
ProjecturedPrimitive = {path = "../../primitive/main"}
ProjecturedProjection = {path = "../../projection/main"}
ProjecturedStyle = {path = "../../style/main"}
ProjecturedSyntax = {path = "../../syntax/main"}
ProjecturedText = {path = "../../text/main"}
ProjecturedWidget = {path = "../../widget/main"}
ProjecturedXml = {path = "../../xml/main"}
ProjecturedYaml = {path = "../../yaml/main"}
