authors = []
name = "ProjecturedVideo"
uuid = "8d225f56-7fda-4c1e-a58b-db6d64f8335c"
version = "0.1.0"

[deps]
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
ProjecturedEssentials = "abe497b7-f7c3-4d23-8caf-a4d4ca8b23b4"
ProjecturedKernel = "a3e3499a-684d-4df9-a0d6-de2d1797b1f3"
ProjecturedPlatform = "b21cb890-5227-4e91-ae0e-8ab4d844f9f7"
ProjecturedSDL = "f0002b97-94ba-416c-b93c-86cdc095626f"

[sources]
ProjecturedEssentials = {path = "../ProjecturedEssentials"}
ProjecturedKernel = {path = "../ProjecturedKernel"}
ProjecturedPlatform = {path = "../ProjecturedPlatform"}
ProjecturedSDL = {path = "../ProjecturedSDL"}

# AutoIntegrations loads this package when Projectured and FFMPEG are loaded,
# unless the environment of the user sets it to "manual".
[auto-integration]
default = "auto"

[auto-integration.triggers]
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
Projectured = "92922de3-b970-4d9a-8b2a-9d6f361397b5"
