name = "ProjecturedFileWatching"
uuid = "24009341-db0c-4146-9c93-d6004d091689"
version = "0.1.0"
authors = []

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
ProjecturedPlatform = "b21cb890-5227-4e91-ae0e-8ab4d844f9f7"

[sources]
ProjecturedPlatform = {path = "../ProjecturedPlatform"}

# AutoIntegration loads this package when Projectured is loaded, unless the
# environment of the user sets it to "manual".
[auto-integration]
default = "auto"

[auto-integration.triggers]
Projectured = "92922de3-b970-4d9a-8b2a-9d6f361397b5"
