module ProjecturedExample

using Projectured
using Profile
# The harness core (the `Example` struct + the seam-based image/video entry
# points) lives at the bottom of the example-package DAG; the name-lookup
# variants defined here add methods to the imported functions.
using ProjecturedKernelExample
using ProjecturedVisualExample
using ProjecturedDomainExample
import ProjecturedKernelExample: Example, write_example_image, record_example_video,
                                 make_typein_gestures
import ProjecturedVisualExample: print_example, write_example_pdf
# `run_example(name)` / `run_example(names)` below add registry-lookup methods
# to the gallery entry point; the tooltip/window composition helper is what
# LiveExamples shares with the gallery.
import ProjecturedDomainExample: run_example, _multi_window_projection

# Re-export the lower example packages' entire public API so
# `using ProjecturedExample` keeps providing every example and factory
# unchanged — the per-name `import` form also lets this module add the
# name-lookup method variants below.
for _src in (ProjecturedKernelExample, ProjecturedVisualExample, ProjecturedDomainExample)
    _srcname = nameof(_src)
    for _n in names(_src)
        _n === _srcname && continue
        Core.eval(@__MODULE__, Expr(:import, Expr(:(:), Expr(:., _srcname), Expr(:., _n))))
        Core.eval(@__MODULE__, Expr(:export, _n))
    end
end
# Loaded so the assistant example can use a real Claude model when
# ANTHROPIC_API_KEY is set: it defines the `AnthropicLlm` backend and its
# `stream_turn` method, which `WorkbenchAssistant` discovers by reflection.
# The assistant *example documents* pass an explicit `FakeLlm` for offline use.
using ProjecturedLlm

# The opt-in examples that need a live database (ODBC) or the native graph-layout
# engine (ProjecturedAdaptagrams C++ shim) live in the separate
# opt-in example packages (`ProjecturedOdbcExample`, `ProjecturedAdaptagramsExample`, `ProjecturedTulipExample`), so this base package depends on none of them —
# it precompiles with no native build and no database driver.

const _EXAMPLE_DIR = @__DIR__



include(joinpath(_EXAMPLE_DIR, "Examples.jl"))
include(joinpath(_EXAMPLE_DIR, "Catalog.jl"))
# LiveExamples moved to the opt-in ProjecturedSdlExample package (they play in a
# real SDL window / record via ProjecturedVideo).

export catalog, atomic_documents
export BRIDGES, paths, path_sequences, projection_to, runnable, catalog_domain
export EditorDomain, EDITOR_DOMAINS, editor_domain, build_file_editor, run_file_editor, warm_file_editor
export EXTENSION_DOMAINS, domain_for_path
export make_json_document_example, make_json_projection_example
export make_json_sorted_projection_example
export make_json_null_document_example, make_json_null_projection_example
export make_json_insertion_document_example
export make_json_string_document_example, make_json_string_projection_example
export make_yaml_document_example, make_yaml_projection_example
export make_xml_document_example, make_xml_projection_example
export make_mixed_document_example, make_mixed_projection_example
export make_natural_document_example, make_natural_projection_example
export make_syntax_document_example, make_syntax_projection_example
export make_text_document_example, make_text_projection_example, make_text_with_image_example
export make_plain_text_document_example, make_plain_text_projection_example
export make_object_document_example, make_object_projection_example
export make_object_to_widget_document_example, make_object_to_widget_projection_example
export make_nested_object_to_widget_document_example
export make_line_numbering_document_example, make_line_numbering_projection_example
export make_text_to_string_document_example, make_text_to_string_projection_example
export make_word_wrapping_document_example, make_word_wrapping_projection_example
export make_text_filtering_document_example, make_text_filtering_projection_example
export make_text_highlighting_document_example, make_text_highlighting_projection_example
export make_widget_document_example, make_widget_projection_example
export make_widget_text_projection_example
export make_widget_label_document_example, make_widget_text_document_example
export make_widget_checkbox_document_example, make_widget_button_document_example
export make_widget_tooltip_document_example, make_widget_menu_item_document_example
export make_widget_menu_document_example, make_widget_toolbar_document_example
export make_widget_composite_document_example, make_widget_title_pane_document_example
export make_widget_split_pane_document_example, make_widget_scroll_bar_document_example
export make_widget_scroll_pane_document_example, make_widget_transform_pane_document_example, make_widget_shell_document_example
export make_widget_tabbed_pane_document_example
export make_widget_badge_document_example, make_widget_separator_document_example
export make_widget_card_document_example, make_widget_switch_document_example
export make_widget_progress_document_example, make_widget_slider_document_example
export make_widget_radio_group_document_example, make_widget_avatar_document_example
export make_widget_alert_document_example, make_widget_skeleton_document_example
export make_widget_toggle_document_example, make_widget_toggle_group_document_example
export make_widget_select_document_example, make_widget_textarea_document_example
export make_widget_accordion_document_example, make_widget_table_document_example
export make_widget_tree_document_example
export make_widget_popup_document_example, make_widget_popup_projection_example
export make_layout_document_example, make_layout_projection_example
export make_constraint_layout_document_example, make_constraint_layout_projection_example
export make_book_document_example, make_book_projection_example
export make_markdown_document_example, make_markdown_projection_example, make_markdown_rendered_projection_example
export make_filesystem_document_example, make_filesystem_projection_example, make_filesystem_widget_projection_example
export make_navigator_document_example, make_navigator_projection_example
export make_collection_document_example, make_collection_projection_example
export make_reversing_projection_example
export make_filtering_projection_example
export make_searching_projection_example
export make_sorting_projection_example
export make_focusing_document_example, make_focusing_projection_example
export make_workbench_document_example, make_workbench_projection_example
export make_assistant_document_example, make_assistant_projection_example
export make_table_document_example, make_table_projection_example
export make_graph_document_example, make_graph_projection_example
export make_math_table_document_example, make_math_table_projection_example
export make_lazy_document_example, make_lazy_projection_example
export make_lazy_bidirectional_document_example, make_lazy_bidirectional_projection_example
export make_math_document_example, make_math_projection_example
export make_julia_document_example, make_julia_projection_example
export make_formula_document_example, make_formula_projection_example
export make_graphics_image_projection_example
export make_primitive_string_document_example, make_primitive_string_projection_example
export make_database_instance_document_example
export make_sql_document_example, make_sql_syntax_projection_example
export make_sql_nested_document_example, make_sql_nested_syntax_projection_example

export make_graphics_caching
export make_scrolling_document, make_scrolling_projection
export make_workbench_document, make_workbench_projection
export make_introspection_document, make_introspection_projection, EditorIntrospection
export make_text_configuring_projection
export Example, examples, run_example, run_console_example, print_example, write_example_image, write_example_pdf, record_example_video, make_typein_gestures
export make_json_console_projection_example
export record_assistant_conversation_video
export json_typein_live, json_select_and_edit_live, json_insert_live, json_build_live, json_build_example
export generate_example_screenshots, update_guide_screenshots
export json_example, json_sorted_example, json_insertion_example
export yaml_example
export xml_example, mixed_example, natural_example, syntax_example, text_example, plain_text_example, text_with_image_example
export object_example, object_to_widget_example, nested_object_to_widget_example, line_numbering_example, word_wrapping_example, text_filtering_example, text_highlighting_example
export widget_example, widget_tabbed_pane_example, widget_text_example
export pane_example, empty_pane_example, pane_json_example
export widget_label_example, widget_checkbox_example, widget_button_example
export widget_button_action_example, widget_button_image_example
export widget_tooltip_example, widget_menu_item_example, widget_menu_example
export widget_toolbar_example, widget_composite_example, widget_title_pane_example
export widget_split_pane_example, widget_scroll_bar_example, widget_scroll_pane_example
export widget_transform_pane_example
export widget_shell_example
export widget_badge_example, widget_separator_example, widget_card_example, widget_switch_example
export widget_progress_example, widget_slider_example, widget_radio_group_example
export widget_avatar_example, widget_alert_example, widget_skeleton_example
export widget_toggle_example, widget_toggle_group_example, widget_select_example
export widget_textarea_example, widget_accordion_example, widget_table_example, widget_tree_example
export widget_disabled_example, widget_focus_example
export layout_example, constraint_layout_example, book_example, markdown_example, markdown_rendered_example, filesystem_example, navigator_example
export collection_example, reversing_example, filtering_example, searching_example, sorting_example, focusing_example, table_example, math_table_example, graph_example, workbench_example
export lazy_example, lazy_bidirectional_example
export math_example
export julia_example
export graphics_image_example
export rotating_vector_example
export make_rotating_vector_document
export assistant_example
export conversation_example
export conversation_widget_example
export conversation_editor_example
export sql_syntax_example
export sql_insert_syntax_example
export sql_update_syntax_example
export sql_nested_syntax_example
export make_clipboard_document_example, make_clipboard_projection_example
export clipboard_example
export make_versioning_document_example, make_versioning_projection_example
export versioning_example
export make_dragging_document_example, make_dragging_projection_example
export dragging_example

end
