name = "ProjecturedFsm"
uuid = "9482bca5-e1c6-47fd-ab22-f4512ed15b91"
version = "0.1.0"
authors = []

# The finite state machine domain.

[deps]
ProjecturedGraph = "cfb0314b-b1fd-4c94-91d2-2de69579dcb1"
ProjecturedJulia = "8625b742-6071-4be0-bd92-d89876019251"
ProjecturedKernel = "a3e3499a-684d-4df9-a0d6-de2d1797b1f3"
ProjecturedPlatform = "b21cb890-5227-4e91-ae0e-8ab4d844f9f7"

[sources]
ProjecturedGraph = {path = "../ProjecturedGraph"}
ProjecturedJulia = {path = "../ProjecturedJulia"}
ProjecturedKernel = {path = "../ProjecturedKernel"}
ProjecturedPlatform = {path = "../ProjecturedPlatform"}
