name = "ProjecturedChart"
uuid = "015a7010-be44-4818-8ca4-bb4593b6d5fe"
version = "0.1.0"
authors = []

# The chart domain.

[deps]
ProjecturedCollection = "8bcd16db-087d-4f4f-9083-436e400a73ed"
ProjecturedDomain = "56e9f339-7147-459f-9ae1-7785cace5f24"
ProjecturedGraphics = "1c8b1e52-4ccf-4c64-9c0e-2a7ed969bd51"
ProjecturedKernel = "a3e3499a-684d-4df9-a0d6-de2d1797b1f3"
ProjecturedPlot = "fab29e63-3751-46a0-88a9-22680e33c7d8"
ProjecturedStyle = "dbc249a4-36d3-4338-9eae-7cc9f61f07b1"

[sources]
ProjecturedCollection = {path = "../ProjecturedCollection"}
ProjecturedDomain = {path = "../ProjecturedDomain"}
ProjecturedGraphics = {path = "../ProjecturedGraphics"}
ProjecturedKernel = {path = "../ProjecturedKernel"}
ProjecturedPlot = {path = "../ProjecturedPlot"}
ProjecturedStyle = {path = "../ProjecturedStyle"}
